# GEMA CARRETERO RIVAS
Problema 2

In [1]:
%load_ext sql

In [2]:
!pip install gdown==4.6.3
!gdown 1Osmr7qVN0NMuqYxvLesNn7H4nqPCVbsU

Collecting gdown==4.6.3
  Downloading gdown-4.6.3-py3-none-any.whl (14 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown==4.6.3) (3.13.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown==4.6.3) (2.31.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from gdown==4.6.3) (1.16.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from gdown==4.6.3) (4.66.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown==4.6.3) (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown==4.6.3) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==4.6.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==4.6.3) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==4.6.3) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==4.6.3) (2023.11.17)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown==4.6.3) (1.7.1)
Installing collected packages: gdown
  Attempting uninstall: gdown
    Found existing installation: gdown 4.6.6
    Uninstalling gdown-4.6.6:
      Successfully uninstalled gdown-4.6.6
Successfully installed gdown-4.6.3
Downloading...
From: https://drive.google.com/uc?id=1Osmr7qVN0NMuqYxvLesNn7H4nqPCVbsU
To: /content/data_berka.db
100% 70.2M/70.2M [00:00<00:00, 234MB/s]

In [3]:
%sql sqlite:///data_berka.db

In [4]:
%%sql
SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';

 * sqlite:///data_berka.db
Done.

[('DISTRICT',),
 ('ACCOUNT',),
 ('TRANS',),
 ('CLIENT',),
 ('DISPOSITION',),
 ('CREDIT_CARD',),
 ('LOAN',),
 ('PERMANENT_ORDER',)]

**Problema 2**

Realizar un análisis de clustering sobre los distintos distritos de la República Checa basado en las siguientes características: A4, A5, A6, A9, A10, A11, A13, A14, A16 de los datos de la tabla district. Sería necesario indicar en cuántos grupos se dividiría y las características de cada uno de los grupos.

In [5]:
data_district = %sql SELECT * FROM DISTRICT
df_district = data_district.DataFrame()

 * sqlite:///data_berka.db
Done.

In [6]:
df_district[["A4", "A5", "A6","A9", "A10", "A11", "A13", "A14", "A16" ]]

         A4  A5  A6  A9    A10    A11   A13  A14    A16
0   1204953   0   0   1  100.0  12541  0.43  167  99107
1     88884  80  26   5   46.7   8507  1.85  132   2674
2     75232  55  26   5   41.7   8980  2.21  111   2813
3    149893  63  29   6   67.4   9753  5.05  109   5892
4     95616  65  30   6   51.4   9307  4.43  118   3040
..      ...  ..  ..  ..    ...    ...   ...  ...    ...
72   182027  17  49   7   56.4   8746  3.74   90   4433
73   323870   0   0   1  100.0  10673  5.44  100  18347
74   138032  67  30   5   64.6   8819  5.66   99   4505
75   127369  31  32   7   51.2   8369  5.88  107   2807
76   148545   8  35   4   53.5   8909  5.56  113   3590

[77 rows x 9 columns]

Aquí podemos observar las caracteristicas de cada grupo:

In [7]:
df_district[["A4", "A5", "A6","A9", "A10", "A11", "A13", "A14", "A16" ]]
df_district.describe()

,A1,A4,A5,A6,A7,A8,A9,A10,A11,A13,A14,A16
count,77.000000,7.700000e+01,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,39.000000,1.338849e+05,48.623377,24.324675,6.272727,1.727273,6.259740,63.035065,9031.675325,3.787013,116.129870,5030.831169
std,22.371857,1.369135e+05,32.741829,12.780991,4.015222,1.008338,2.435497,16.221727,790.202347,1.908480,16.608773,11270.796786
min,1.000000,4.282100e+04,0.000000,0.000000,0.000000,0.000000,1.000000,33.900000,8110.000000,0.430000,81.000000,888.000000
25%,20.000000,8.585200e+04,22.000000,16.000000,4.000000,1.000000,5.000000,51.900000,8512.000000,2.310000,105.000000,2122.000000
50%,39.000000,1.088710e+05,49.000000,25.000000,6.000000,2.000000,6.000000,59.800000,8814.000000,3.600000,113.000000,3040.000000
75%,58.000000,1.390120e+05,71.000000,32.000000,8.000000,2.000000,8.000000,73.500000,9317.000000,4.790000,126.000000,4595.000000
max,77.000000,1.204953e+06,151.000000,70.000000,20.000000,5.000000,11.000000,100.000000,12541.000000,9.400000,167.000000,99107.000000

Lo dividiriamos en 3 grupos.

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
import random